### PR TITLE
nuget package

### PR DESCRIPTION
**Pull request by rhwy**
Hi Craigg,

This patch is not a great thing, but for a demo I done at techdays paris, I used your fluent-mongo over official driver and it was really great. For that purpose, I added simple stuff to create the the nuget package. 
It should be good for people to have your fluentmongo library on the offichial nuget channel if you aggree with that. If you are not, tell me just if I can redistribute through my blog this package to allow people to use my samples in a simple way.

thanks for this great project!

cheers!

Rui

### CODE REVIEW

**Comment by craiggwilson** [comment]
Hey, this is awesome. I've been meaning to do this.  I'm thinking maybe I should change the name here over to something more suitable, like mongo-csharp-driver-contrib.  We can have seperate nuget packages for each feature if necessary.

Question, does mongo-chsharp-driver have a nuget package we can reference? (I haven't look at your implementation yet,)

**Comment by rhwy** [comment]
Hi Craigg, thanks for your reply.

Yes the official driver is available through nuget package and the best to do in this case is to reference directly the original package in order to mark it as dependency in our package. The problem is that the official nuget package seems to be 3 versions late from the one you are referencing in from the github sources (and I didn't want to change your project structure too ;-)). 
I'll make a try modifying your sources to point to the official nuget package and verify if it compiles and if the tests run.

A last point. It should be essential for me to have a simple way from the application using your framework to have a way to get a dump of the command executed for profiling. It seems not to be so complicated, but I didn't go too much deeper in your sources and you may have a better to expose that. What do you think?

thanks

**Comment by craiggwilson** [comment]
1) The package available in nuget is not compatible with the currently released version, and therefore with the fluent-mongo package.  So, until they get their act together (maybe I'll open a jira for it), then we'll need to use our own reference unfortunately.

2) You need logging statements or something like that?  Maybe just a hook?  Underneath, I'm doing nothing but building up a query and then running that through the driver and interpreting the results.  I think what you are looking for would be something that should come out of the driver and not the linq provider.

3) Thoughts on mongo-csharp-contrib?  I'll run it by the 10gen guys.

**Comment by rhwy** [comment]
Hi Craigg, a few updates :

1) I unfortunately arrive to the same conclusion
2) I added in my fork a simple extension to dump MongoQueryable command info and updated MngoQueryTests.Chained to test it. It should be better to hack the driver directly to get info for all commands (and get also stats from the response) but if fits not so bad for me as a first level of query trace.
3) mongo-csharp-contrib will be great. If we can add an 'official community module' on top of the official driver it should be really nice and possibly help driving efforts in a common way (avoiding the growth of plenty of small hacks around the world ;-). So, +1 for the contrib, I hope it will be usefull/successfull as the mvccontrib one.

**Comment by craiggwilson** [comment]
ok. I'll get your stuff pulled in tomorrow and then I'll change the project name to mongo-csharp-driver-contrib.  I talked a little with robert stam at 10gen and he said they could probably host it in their organization, but it wouldn't be for a month or two.  Therefore, I'll host it on my account and hopefully they can take it up at a later date.

**Comment by rhwy** [comment]
Great, that's a good news! 
thanks for this project ;-)

**Pull request merged**
