### PR TITLE
Update to mongo csharp driver 1.1

### PR DESCRIPTION
**Pull request by jonnii**
LMK what you think.

Thanks!

### CODE REVIEW

**Comment by jonnii** [comment]
Sorry that the commit is from 'unknown' but this isn't my usual dev machine.

**Comment by craiggwilson** [comment]
Awesome. Looks good.  I'm going to bump the version to 1.1.0.0 to stay in sync with the driver.  I'll try and get this done today.

**Comment by jonnii** [comment]
That works for me.

**Comment by jonnii** [comment]
Any news on a new version?

**Pull request merged**
